[package]
name = "mindforge"
version = "0.1.0"
description = "MindForge Desktop"
authors = ["MindForge"]
edition = "2021"

[dependencies]
# 统一使用 2.x 稳定分支，由 Cargo 自动解析到最新兼容版本
tauri = { version = "2", features = [] }

[build-dependencies]
tauri-build = { version = "2", features = [] }
